# Generated by Django 5.2.5 on 2025-11-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descicao',
            new_name='descricao',
        ),
    ]
